### ISSUE TITLE
Basic Kit setup

### ISSUE THREAD

**Issue by PRiCK44** [Protocentral/protocentral_healthypi5_zephyr#15]
I have the Basic Kit (the one without a screen). I can't find any documentation to setup the Basic Kit. I see on the homepage the firmware setup instructions with the Complete Kit (with screen). But nothing for the Basic Kit setup. Please help me set this up with step-by-step instructions or a video. I plan to use with either a PC monitor or as a Raspberry Pi hat which will be hooked up to a different monitor.

**Comment by MishalJasmine** [comment]
@PRiCK44 If you have a Healthypi 5 basic kit, the operating modes of Healthypi 5 available for a basic kit are [Base](https://healthypi.protocentral.com/functionality/01-Base/) and [BLE](https://healthypi.protocentral.com/functionality/02-BLE/). Uploading the firmware to the Healthypi is the same as described in the [website](https://healthypi.protocentral.com/). If you are still facing any issues with the setup, we can arrange for a zoom call.

**Comment by PRiCK44** [comment]
Hello,
Thank you for contacting me. I did read the website, but it shows in step 2 that "booting up the device will show the following screen". 

Because mine doesn't have a screen, how do I know its ready to program? 
How do I know it's in program mode? 
Can you just tell me in this email the steps I need to follow?
Thanks you so much

**Comment by PRiCK44** [comment]
![Screenshot_20240229_091106_Edge](https://github.com/Protocentral/protocentral_healthypi5_zephyr/assets/102995403/859d34fb-6968-40d7-b36a-7c40626eff9e)

**Comment by MishalJasmine** [comment]
Hi,

We understand that our website did not answer some of your questions. We
have made some more changes to our website. You can have a look at it as
well.

Follow the simple steps below and you should be able to set up your
Healthypi 5 Basic kit.

Step 1: Connect your device to a computer using an A to C type cable.

Step 2: Switch on the device. If the red LED below the board glows, your
device is powered up.
[image: image-53.jpg]

Step 3: Switch off your device. Locate the RP2040 button below the main
board, near the Spo2 port. Hold the RP2040 button and switch on the device.
Once the device is switched on you can leave the button. It will enter
programming mode. In a Basic Kit, this is indicated by the RPI-RP2 drive
that will appear on your system.

[image: image-31.JPG]

Step 4: The basic kit supports only the Base and The BLE firmware. Drag and
drop the latest firmware version to the  RPI-RP2 drive.

The website also includes a video of the above steps, you can also refer to
that. If you have any questions, please feel free to contact us.

**Comment by PRiCK44** [comment]
Thank you. I was able to get it working with the instructions above. 

![20240304_110219](https://github.com/Protocentral/protocentral_healthypi5_zephyr/assets/102995403/6f2b2210-87b9-4e33-ae31-bf20ad87c5cd)
![Screenshot_20240304_110856](https://github.com/Protocentral/protocentral_healthypi5_zephyr/assets/102995403/826489ac-82a4-420c-a5e8-89bb6b814291)
